### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by infstellar** [xBoyMinemc/FlashFakePlayerPack#26]
[Scripting] TypeError: cannot read property 'currentValue' of undefined    at <anonymous> (lib/xboyEvents/en
tityDeadByHurt.js:3)

可能是在吸取经验时出现的错误

**Comment by xBoyMinemc** [comment]
收到，我们的技术团队正在密切关注您反馈的问题与所在产品，将会在14个工作日内返回书面答复，不包含法定节假日。

**Comment by xBoyMinemc** [comment]
现在应当是解决了的
