### ISSUE TITLE
关于假人创建序号一直叠加

### ISSUE THREAD

**Issue by Tolineking** [xBoyMinemc/FlashFakePlayerPack#29]
是否可以改变序号叠加呢，个人存档现在已经叠加到五六十了

**Comment by xBoyMinemc** [comment]
新版本里有一个重置功能

**Comment by xBoyMinemc** [comment]
commandRegistry.registerAlias('假人重置编号','假人重置序号')
commandRegistry.registerAlias('假人编号重置','假人重置序号')
commandRegistry.registerAlias('假人序号重置','假人重置序号')
