### ISSUE TITLE
请求添加功能

### ISSUE THREAD

**Issue by 2693551060** [xBoyMinemc/FlashFakePlayerPack#33]
大佬，能不能做一个自动挖矿（能使用镐子就行）的功能，我想要全自动刷时机，感谢

**Comment by xBoyMinemc** [comment]
存在 自动挖掘功能
考虑维护一下，更好的满足你的需求

**Comment by xBoyMinemc** [comment]
![image](https://github.com/xBoyMinemc/FlashFakePlayerPack/assets/86919167/76a4f309-4e91-4bdf-8ac2-fb644b41845e)

**Comment by xBoyMinemc** [comment]
https://github.com/xBoyMinemc/FlashFakePlayerPack/pull/34#issuecomment-2207391961

**Comment by 2693551060** [comment]
大佬能留个联系方式吗？我想赞助一点微薄之力
