### ISSUE TITLE
如何創建假人

### ISSUE THREAD

**Issue by AFAlimru** [xBoyMinemc/FlashFakePlayerPack#35]
我找不到教學影片 1.21.2還可以用嗎

**Comment by Yukino002** [comment]
> 我找不到教學影片 1.21.2還可以用嗎

可以，直接在聊天栏输入“假人创建”

**Comment by xBoyMinemc** [comment]
@AFAlimru 输入FFPP或ffpp
在这里找到一个可用的1.21.0x最新版https://wanasleep.github.io/

**Comment by xBoyMinemc** [comment]
我准备了英文（非简体中文）的创建命令

**Comment by xBoyMinemc** [comment]
在聊天栏，发送”ffpp“或”FFPP“
    这是一个英文的创建方式
    而不需要发送”创建假人“这个中文简体语句。
@AFAlimru
