### ISSUE TITLE
aternos可以用嗎

### ISSUE THREAD

**Issue by AFAlimru** [xBoyMinemc/FlashFakePlayerPack#36]
aternos我放packs不能增加 我也不會用 大佬們救救我

**Comment by xBoyMinemc** [comment]
令我困惑哦，你能够添加其他的行为包吗

**Comment by AFAlimru** [comment]
我也不行增加其他套件

**Comment by xBoyMinemc** [comment]
如果你可以阅读英文
可以尝试aternos官方的教程
https://support.aternos.org/hc/en-us/articles/360042095232-Installing-addons-Minecraft-Bedrock-Edition
