### ISSUE TITLE
单人睡觉问题

### ISSUE THREAD

**Issue by ze-t** [xBoyMinemc/FlashFakePlayerPack#37]
请问可以解决单人存档有假人不能睡觉快速跳过黑夜的问题吗

**Comment by bszydxh** [comment]
/gamerule playerssleepingpercentage 0

试试这个？

用法参见https://minecraft.fandom.com/wiki/Game_rule

**Comment by bszydxh** [comment]
https://github.com/xBoyMinemc/FlashFakePlayerPack/issues/27
