### ISSUE TITLE
假人报错并清除实体然后解决的故事

### ISSUE THREAD

**Issue by MoonYueya** [xBoyMinemc/FlashFakePlayerPack#38]
假人会把所有实体（也许只是生物）全都清除
并连续提示使用/reload指令 
当不再报错时，村庄已经一只羊都不剩了

但好消息是，在报错之后退出游戏，进入世界，然后村民奇迹重生

bug触发坏境：iOS Minecraft1.21.2 假人1.21 v2

**Comment by xBoyMinemc** [comment]
whats happen

**Comment by xBoyMinemc** [comment]
我会持续关注这个问题，因为我在所有代码里没找到和kill/remove/despawn其他生物有关的内容。
你可以理解为闹鬼了。
然后我会尽快解决初始化长期存在问题的问题。
