### ISSUE TITLE
装到服务器后运行报错

### ISSUE THREAD

**Issue by PhoenixChou0715** [xBoyMinemc/FlashFakePlayerPack#40]
![20240814_200721_remastered](https://github.com/user-attachments/assets/ee96893b-29c0-4942-a9e0-841da7fa75c1)

**Comment by PhoenixChou0715** [comment]
@xBoyMinemc

**Comment by xBoyMinemc** [comment]
你1.21.20服务端？
没法用，等待更新

**Comment by PhoenixChou0715** [comment]
😭😭😭

**Comment by PhoenixChou0715** [comment]
> 你1.21.20服务端？
> 没法用，等待更新

所以只能是1.21.20以下能用咯😝

**Comment by xBoyMinemc** [comment]
正解

**Comment by xBoyMinemc** [comment]
好了哦
