### ISSUE TITLE
可以说一下这款假人的原理吗

### ISSUE THREAD

**Issue by PhoenixChou0715** [xBoyMinemc/FlashFakePlayerPack#46]
单纯想了解一下这款假人的原理

**Comment by xBoyMinemc** [comment]
MOJAG为了满足游戏测试的需求，自己搓了一个gametest  
然后有部分测试是模拟玩家做一些操作  
然后他们自己搓了一个模拟玩家  
我做的事就是模仿他们  
在世界边界召唤一个他们的模拟玩家  （大部分的bug，初始化问题都在这里）  
再丢你脸上

**Comment by PhoenixChou0715** [comment]
感谢大佬解答  ᖰ⌯'▾'⌯ᖳ
