### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by zhangzy0203** [xBoyMinemc/FlashFakePlayerPack#48]
在1.21.2x中，无法使用假人行为包，输入假人帮助和假人创建都不会有效果

**Comment by xBoyMinemc** [comment]
实验玩法中的测试版API开启了的话。看看有没报错吧

**Comment by zhangzy0203** [comment]
没显示啥报错，我记得应该是ojang删除了假日创作者导致的，以前1.20还能用的，同样被害的还有MQ连锁采集和一部分addon，你可以自己尝试一下试试有没有问题，建议以后开发先测试一遍再发布谢谢

**Comment by xBoyMinemc** [comment]
语气好一点，大家都能用。不要用这种审判的语气。

这和假日创作者没任何关系。

**Comment by xBoyMinemc** [comment]
至少提供必要的信息，你的版本截图，行为包截图，存档设置截图。
