### ISSUE TITLE
[SUGGEST] 添加重命名假人的功能

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [xBoyMinemc/FlashFakePlayerPack#55]
这样可以方便多人服务器追踪和管理假人状态 :)

**Comment by xBoyMinemc** [comment]
有个简单的
对着说
“假人改名 新的名字”
中间是空格。记不清了大概是这样

**Comment by xiaoyueyoqwq** [comment]
> 假人改名
> 假人换名
> 假人重命名
> 
> 后面会继续改进多人服务器的追踪管理体验的

报告一个问题：即使在重命名假人后在玩家列表内假人名称依旧没有更新，并且在这里也同步一下#56的问题：当不带召唤假人召唤假人时可能会出现调出世界的bug，之后也无法从玩家列表中移除这个假人，这个假人的状态也是未知状态
![bcab228d-1245-42eb-a255-3631d8de51b9.png](https://github.com/user-attachments/assets/b8c4f0f1-5e5b-4049-a6a8-c1c1153fa047)

**Comment by xBoyMinemc** [comment]
鬼

**Comment by xBoyMinemc** [comment]
没辙。我暂时没辙。以后有机会了再处理
