### ISSUE TITLE
[SUGGEST] 改进bot生成功能

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [xBoyMinemc/FlashFakePlayerPack#56]
我的想法是：既然bot无法被保存的话我们是否可以直接在指定坐标生成一个bot呢？给生成指令加上更多tag来实现更加方便的一键部署

参考：假人生成 x y z name

**Comment by xiaoyueyoqwq** [comment]
> 我的想法是：既然bot无法被保存的话我们是否可以直接在指定坐标生成一个bot呢？给生成指令加上更多tag来实现更加方便的一键部署
> 
> 参考：假人生成 <x>,<y>,<z>

**Comment by xBoyMinemc** [comment]
好主意，有试图推进过这个想法，然后留下来了个坑就结束了

**Comment by xBoyMinemc** [comment]
https://github.com/xBoyMinemc/FlashFakePlayerPack/releases/tag/1.21.20_FFF_1.21.50

**Comment by xBoyMinemc** [comment]
坐标必须 名称和纬度可以空缺

**Comment by xiaoyueyoqwq** [comment]
> 坐标必须 名称和维度可以空缺

功能可能存在bug？
![Uploading AGC_20241102_150127275.jpg …]()

**Comment by kzyqq00-Player** [comment]
> 坐标必须 名称和维度可以空缺

#75 可以只传名称了
