### ISSUE TITLE
[BUG]假人默认生成名称错误

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [xBoyMinemc/FlashFakePlayerPack#58]
如图，如果要使用 假人销毁 指令远程销毁时就会出现无法分辨假人的问题，并且假人的默认名称也就是 工具人-id 这个名称并不能正常工作
![57c49dd3-2ba2-4d15-9105-ed9fe0388c0a.png](https://github.com/user-attachments/assets/8a45d9c0-e01c-425a-8325-643a5422c9ad)

**Comment by xBoyMinemc** [comment]
什么玩意？？我看看去

**Comment by xBoyMinemc** [comment]
v16#1-21-50解决了
